2023-08-31 10:56:02,659 (48345/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 10:56:02,660 (48345/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 10:56:02,662 (48345/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2023-08-31 10:56:26,691 (48360/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 10:56:26,691 (48360/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 10:56:26,693 (48360/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2023-08-31 10:58:04,373 (48399/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 10:58:04,374 (48399/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 10:58:04,375 (48399/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: neptunespace-production" for connection option "port"\n'
2023-08-31 10:59:21,048 (48430/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 10:59:21,048 (48430/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 10:59:21,049 (48430/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: neptunespace-production:5432" for connection option "port"\n'
2023-08-31 10:59:45,488 (48434/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 10:59:45,489 (48434/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 10:59:45,490 (48434/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2023-08-31 10:59:55,411 (48435/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 10:59:55,411 (48435/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 11:01:10,499 (48435/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: could not receive data from server: Operation timed out\n'
2023-08-31 11:37:43,571 (49189/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-31 11:37:43,572 (49189/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-31 12:12:44,110 (49189/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 630, in connect\n    passwd = click.prompt(\n             ^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/click/termui.py", line 166, in prompt\n    value = prompt_func(prompt)\n            ^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/click/termui.py", line 149, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
